FROM ubuntu:22.04

MAINTAINER FOSSEE <pythonsupport@fossee.in>

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y tzdata
RUN apt-get update -y && apt-get install -y git python3-pip vim libmysqlclient-dev sudo python3-venv python3-distutils && \
	python3 -m pip install --upgrade pip

RUN apt-get install apache2 libapache2-mod-wsgi-py3 python3-django -y &&  mkdir -p /Sites/online_test 

VOLUME /Sites/online_test

ADD Files/requirements-* /tmp/

RUN python3 -m pip install --upgrade 'pip<24.1'
RUN cd /Sites/online_test && pip3 install -r /tmp/requirements-production.txt 

ADD Files/000-default.conf /etc/apache2/sites-enabled/

ADD Files/Docker-script.sh /Sites/Docker-script.sh

EXPOSE 80

WORKDIR /Sites/online_test

CMD [ "/bin/bash" , "/Sites/Docker-script.sh" ] 
