FROM ubuntu:22.04

MAINTAINER FOSSEE <pythonsupport@fossee.in>

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y tzdata
RUN apt-get update && \
	apt-get install -y git python3-pip libmysqlclient-dev sudo default-jre default-jdk python3-venv python3-distutils && \
	python3 -m pip install --upgrade pip

VOLUME /Sites/online_test


# ESP-IDF and QEMU dependencies
RUN apt-get update && \
	apt-get install -y git python3 python3-pip cmake make gcc g++ \
	libgcrypt20 libglib2.0-0 libpixman-1-0 libsdl2-2.0-0 libslirp0 \
	wget flex bison gperf python3-venv ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 \
	&& rm -rf /var/lib/apt/lists/*

# Install ESP-IDF
RUN mkdir -p /root/esp && \
	cd /root/esp && \
	git clone -b v5.5.1 --recursive https://github.com/espressif/esp-idf.git && \
	cd /root/esp/esp-idf && \
	./install.sh esp32

# Set up ESP-IDF environment for all future shells
RUN echo '. /root/esp/esp-idf/export.sh' >> /etc/bash.bashrc
RUN echo "alias get_idf='. /root/esp/esp-idf/export.sh'" >> /etc/bash.bashrc

ADD Files/requirements-* /tmp/

RUN pip3 install -r /tmp/requirements-codeserver.txt && mkdir -p /Sites/online_test/yaksh_data/output /Sites/online_test/yaksh_data/data

WORKDIR /Sites/online_test

ADD Files/Start-codeserver.sh /Sites

EXPOSE 53579

CMD [ "/bin/bash" , "/Sites/Start-codeserver.sh" ]
